{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-api-token-secret",
    "namespace": "cert-manager"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-api-token-secret",
        "namespace": "cert-manager"
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "api-token": "AgDCWcYovsNLLaTjzTiejGIHjoOnj2zA9DyUmWmuurzxb3jWAF50ds/DpcS0yPeddL1HNf+Fw2mfsLUaB/n4+NB2BS1TKTudOB8cwYdmeXOyi+EycWEiu/FtIhB0Z6RNp/ybxjHrRIz/YLWe667jGlT5n7OEjUgsy+/I3zKUzq5B2ZYbRSD8Js11E1waY0/3Ivb7NEHob4h8hSnhjxSDsVsc0EbFBFZlGUe6g7XcN/InRiwegh8P6VCvwkP9ytHdVsQomFnXgnsF+rHNa6U2d8gC0b919pNTMxg0hfHDXhHnePhwLuh4HrZbhJAxjMxSRD8WTsKiR3sjYwVSposnz/XszG5fELN6uTIWQlYF8LlX/D7RBvGNWEBpvHI6Imsmo7Z7kFarCZ+jS5XVaknSL9BY2viFN0ghlAQKwyk/Wk9l3KGfU+XUZd5sovTYfz9Vf0Xb9OaTlHR3aixrIfoZMwodBqHIbcMfsHmFAZkykeAVnfk2XhcMCUNqcSvvn27pJkS3qTC58bB6Z74nsQx/vwI5Bia4UyQUJmTXVtP2xVXw1eqTkhQlYWArorA8acsF/vIFmA16NXiOActIowaka4rh3KT+7L/IRx0PIEfAHBbkcbRDO7cDwMEYdIh3TEgeLCbtgxAVGc7r9Q3hT0ikuSjxLlY6BU+m6tzGuIDgnXzBAwjGv6/F5QX2h1xuhfiMofv7ZKbAqz8OTMkon9lDoRIJLHgaHDIFbW7vS/bHTaA1wQOndhC4RHKc"
    }
  }
}
