---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: redis
spec:
  encryptedData:
    password: AgAarIprJOfYKGUcsMyaS8aLXJwlRFPBk84ly7iWehuF1Q0ZgTuW1vIQKTkGWa45oMmL9wwts48CkxPAjlq7+Pk63jcEvrQ19FwMGxmfDc2E3qGLOq+/uSSbHkyBebQDPAVs49UF7jwAnvHBZQ26a+VfnbpZX4a26JgNvXEmXumrDbV6gMc/ogGg4uCtkTiBDM+ZURhPCE94g6Z6d0FGk2CjHUMDVrr4TlpDS5qIIhRdjODrwHzrSoFZAYOqsBnT1BBVVMz9yk/L0trzQApJGyzO6dJRPB/JEdzHvKQsuy9+/kAQr31UE+SNqO+V2Czyk8WLxMmPgVOQxnG5UTZ71ZENqW346a6u4wbj9xFT/6yQvqg7ufnsMG2ovut/mDSoYZ//Vqhrsq8HNAxk76NM6S2aFrGbPl5UgLjNyYil6mR/GuJcvfp9wp+psAtAfc3dp6UgebtGBW0zw7zR5lLYEAwHfivSIY6B227A/uIZDg7I9IAm0wMS7SVsWRZbrqYKy64dUs0SFShWw87NYvS7ekDlFqyeMnD56NWRg8+r9ld+1TuH/KKusXTATzo4jaWuauS9+Gr+33FkVsLzjEL92saRnwQA8UZr9dzOFcwgrZJV5JF2/Ei+hVUTc9B1FFb4kKjIyMxvIBRp0cGp1V7YkoebKpvr33lTvjki3aUL1XJHWiFh6zShG0PCUNnQweWuoJ5sAYe6PAzmVNx5T62t9/6ve7XBSwejREIRNEyi6+RdakYBoMsJ9llirDoJ4pYxhWwiX7E55vW4KBNqhdwqQyV6
  template:
    metadata:
      name: redis-auth
      namespace: redis
    type: Opaque
