---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-auth
  namespace: minio
  annotations:
    # Helm 차트가 만드는 Deployment보다 먼저 Secret이 존재해야 하므로 PreSync
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    rootPassword: AgB0HTPosPq0P2KduLOFmknU0zI0tNBRd9LplEg8ypSNtIbUwUNTfwh9v139XtetHRrzL0/navfXUehhmmlVVoRGQZAaHWsciksPSwgqHbV6w/zs8n0gQXM6klqOFm3zrUCeGVdH1Zh1r5++RCy511ecdXcGmuQARSEz+XTsPi8H+L58NLU3y8oHldn91gkHnd3QukLgyhck4HWIcCZKitJK0XnYje3aV8TvKKtp2u3FtFP+xgz9hbsjbTq+xqtEIDHVL8pZzqKZXsCvjaD61iMXusXTnbZApGKGdenKg642Ea5UoboTUtNZYYDC07g8ELKmyptiZQNM1eRGT/OBqjeVdWv395ylyPku9a/Y0xj6F9yO+KZjKb6SosepFf1LMzZx2Iq4k1Vbk1O1vNG6UX0OSiROqSTt0q6voFLHr8HiDZe8JvLoMlbrbgXkFXQcLoJ2IZJTRGpBDJPQ9rU+KBe/n80tY8t5cOXwDJRmGL8MELJwJ2mrOP/Pm+3PvGQMWgmGuzvTDvY+JiC94d7qD1lr9ts+fYbxyVSJO9WM5mjQeAkaWREV0z3jBCJIU9hVhTiZazNSw4Gt+DVn3vWzXOmwgBPmXULRuwWKuKxbwfqmr5kRR4XdPbodQ6HHAJLYt0cE0XhEgWe3m5gyT3TK1z9p3put+4Wj7uNh8qnByjHoCfvtxvRD/Kr++fiKBB6UxGO78Y71HGg4fgTj4czq/knCIPKoHvonqJ4Ux0fp2ZE9
    rootUser: AgA3ak+LTSYQAzQpF7Gf97W/OWdMhsi6kjMaCUI6/hSr3NhwjZMp4M+q7CnGCTKttB0LHRymdAG96ksq+xhtUO7EQCX8jrFBsRDWkSjVec+XBxZzoWtGnbote72dA4Q5qLBl7g1A8wblFbm21jG8v4a3c++POetaU/W54DyMiw3x4wMP3RqVFkrDQserV4i/AyNkGYbyt/MtR+MOmHu9T/1A3TbrDx21SbP22ffqgtPrdy+nGysBuCK/og8qI8OwuZrrSOpKVoOW2QDKA57VccA++YRs8eXqvOzcXUul9555eVnANEl/yT4ed3MCPHyReU9cabuhEDS5BNwQOkkrwMG3NH7E7d7W1g4Eumixgk8NyJr788qPxPLdNQ11w6Qr60Y7S8iP4GCVOxdQiBNP44dG9/BYhn1qSWeUDsSOckNXqtIKAmfFl5+J+J4lv1C9DMIHB1jKtTIcZ5FX/EOEzSuX0QXBQAG/GjmR6DIscHNOtuETGj3XHqyDtNU17WVnKo+BOnDQ91RezHcgNGT76g/dg2i9uCZp4aDPRn+UzuwVhS1ezylAs34ZZdmD9CMIlFhCNLMHAP6SdUAJFHmnWWhG8kMoF7Jt9L49LxsFRHGaJi0EtN6LpgtGDLvr10x3EUTbjmqnlywUmYCndG/r7h4hE6JDcVAUer9inzsnFO8bGECgTWtEb1H7ZLFBtEfmqQZ2d87GnEVdgd7l
  template:
    metadata:
      name: minio-auth
      namespace: minio
      annotations:
        argocd.argoproj.io/hook: PreSync
        argocd.argoproj.io/sync-wave: "-1"
    type: Opaque
