---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-auth
  namespace: postgres
spec:
  encryptedData:
    password: AgAib9Xsw1TyubuZdSXvM9lJ5ZincfFHRH8lORbYI6K2CrNEzci/ROhbAccpE+UcyeM+OAyJF0jlW6NC1QsOp0wupl1xjPSvsXDV7ODCjwQPwlLF1LCpEIuInIiDB8V42ecEn9CBoiI7odP7H1pg+e1/MKp9ZhhDd5hgV4LlYIA/k3VMpIoTJnn8o2KIwfIKPCwAogPAC08OcDRRNhAr12/7b9P+D+671VP29bScDmJF3iHFRPpUv5886kSxHZzET7TydI8qgvdkNqQbEtyTZSf7ResNV3kCbk3uYC7n4nrJAJW5DaXB0J1jruZm8gkSHjcqaQFAEOnl7jpU0XhqVXM/Msgi5jX16C8tDqn9oXN/Mqswu4OfDLZcFrLSuun7dQwioY7ex9W4vYjoDuzfQfS/hP3VIkfXo1rVrNSCkofQLqOd0r6xcVcW/NlrAVto2u4CrKQQsXR4poIaH7NeJrlFvuYHy7aeo0q7trnH7cU2DsZr3B7gYG+oPBEoRiN2S6tKcJais+B7V3n5Dm+he+ZXv854GQwYHBENUvsgYtJ7U3f9814kFsv9sG7lObEJr4VuKOAfrxJGtT+fvft5qAhLBwuS68YZ+yAhKOhGhqpQgwsXlBG1ut42P1Z5yHZP+i36U+BY7aRNvpuI4Ogk5cgSxj84c0Obng4zANBwUnZaDgDAOH0LFeYohZOFAtzgP0NOkRtf2VVMrJ7Iv0tyE8ql6s4L4ztDL6wJgVWYkLqO98VgufuEXEWoCr/VYRsJLSAXppEgC2tWJfCpkbC3VER6
    username: AgAUM2/Zd4jBehKO+WpiNd0DgBr4wnm/IxWWagGFHJbVuGiDyWhyVhijkyfKWY5h3JFL2Oi89TH1Wbb1+2HfNN1XkFFn4uQQo41RIxMoc9+UX+fFOzQFEcw5IEJt2rtkXnQKHpSiUv2lXEgG/Zhi1P4Aki5lfKm0AhhJgLp6iV1PwAm/3g3EmPyJaaeGCCnb//8gaxydVqFshcaax2udAx0St/YhCENgVRHTLAnpxFND7uL5XeHIUOOjGvvINTayu4L+qes4t18Rgxiwc38zyXivKi1XMRGxk7Oc2/V0UiV4WJCmEiy8N1gl3fXImJqYxwJYij2G4QFWIBzQmc9zItS6TRPJDECNcB1zidUzE4p2AAw/E2dIi5LEk/klKGTBoZWdgC3q5IkQ/Z3UK7Itt+EhkSor0TWv4fFe8enyTIGG96AadBOurm0h7W6P2KOG2CV4JPMs/npo80J5k9Ex26tInKKwjt8R/7jRcSvZPG/5S/nXLt3cYMqC+nwM7vbsHwXFdItrDKsByNMqOaCInBeq/oUOllGLzNdWIsEeInbGYsNWs9nhkqlN6VIdocEGdHg7PEnFLjnmXWF7jMm+uVZgZN3gi/KXUXNRNYchZ6ltn1rOpiH0hBAD1xlkHRMocmvgluN75VUyqck5JjJvrJCXFYBIK2pveeQHOGiXmQfjtSQJqR3Ck5PGN39sC6F+zKXXGZhgNw==
  template:
    metadata:
      name: postgres-auth
      namespace: postgres
    type: Opaque
