{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "github-api-token-secret",
    "namespace": "arc-systems"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "github-api-token-secret",
        "namespace": "arc-systems"
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "github_token": "AgCWmKKo9mJGbepYUtGgLClbqAt94akMO+6qTgOTIbMUbognzMWjPo5+Kga6IWaq0SZqczVACDGcf97fbXMPmXhqgG211ZZwSeho/GEDV02VZtOkwawaf0CfXtt+iDeT6OqFOkHhrH2Z+UDafdX3j3nfGWBihXOO7wQJnIsgHAcPEhNouAD41nCpGnSO//C65jAyZEARb85HFQTX6c3FCg7qHU9rpe5kC2CIFSxIvUwFyChv4se5wit3xXluyKHBBupsBkuqz5kEpngWkC446VKwFUnJJD9UJLWpvS3VlkgelIgiGZ+19io2GztuXTMpTqoVCE+CPUFC0MJpNWNzVBAQ0a3Y5fZPYGfogWQh0LVCog2y9HyZv4a3Gh+mTn/CXsPk3rUwmSCdJV1OechAiqPvABvqmSitTkjF0+k4BiOdRXFLM0cy6cJ3KK2YxoMnmoV9ez6DcRGQ5VWTSNgKVyKXqzAttLYPVNtZ7rHsomF7A3hrU5FN2vbk1viI1oiGDFd7ynkGU2eRa5yC69Q+9fEflXzR+hdGqDyd4zUdMG1X3scZRbvtp5WeVFW4CRc8pfyxACospxC3W9WZ0xhp4p74KbqDG627vZ+fQAc8ZQWo9TzRR8skLTwQpUSvOO7bwII4DbHw5Xuz3liNRCyhN7kSwC0RtLuUXMmSHrYswIpKAFXUn1KQcLLY9BRph8FGJ1fD/LkczEI0sSQNaMEWPlQ6Y7STSgHLTPtW2EbTbPmqSzPwUIoTRr+N"
    }
  }
}
